import { describe, it, expect, beforeEach } from 'vitest'
import { ClaudiaCodeParser } from '../src/parsers/claudia-code-parser'

describe('ClaudiaCodeParser', () => {
  let parser: ClaudiaCodeParser

  beforeEach(() => {
    parser = new ClaudiaCodeParser()
  })

  it('should process assistant messages normally', async () => {
    const testData = `{"type":"message","timestamp":"2025-11-12T16:55:45.575Z","message":{"role":"assistant","content":[{"type":"text","text":"Hello! I'm doing well, thank you for asking!"}],"api":"anthropic-messages","provider":"anthropic","model":"claude-sonnet-4-5","usage":{"input":3,"output":117,"cacheRead":0,"cacheWrite":1196,"cost":{"input":0.000009,"output":0.001755,"cacheRead":0,"cacheWrite":0.004485,"total":0.006249}},"stopReason":"stop","timestamp":1762966540939}}`

    const results = await parser.parse(testData)

    expect(results).toHaveLength(1)
    expect(results[0].content).toBe("Hello! I'm doing well, thank you for asking!")
    expect(results[0].role).toBe('assistant')
  })

  it('should handle mixed valid and invalid messages', async () => {
    const testData = `{"type":"message","timestamp":"2025-11-12T16:55:40.961Z","message":{"role":"user","content":[{"type":"text","text":"Valid user message"}],"timestamp":1762966540936}}
{"type":"event","timestamp":"2025-11-12T16:55:40.961Z","event":{"type":"message_end","message":{"role":"user","content":[{"type":"text","text":"Valid user maessage"}],"timestamp":1762966540936}}}
{"type":"message","timestamp":"2025-11-12T16:55:45.575Z","message":{"role":"assistant","content":[{"type":"text","text":"Assistant response"}],"api":"anthropic-messages","provider":"anthropic","model":"claude-sonnet-4-5","usage":{"input":3,"output":117,"cacheRead":0,"cacheWrite":1196,"cost":{"input":0.000009,"output":0.001755,"cacheRead":0,"cacheWrite":0.004485,"total":0.006249}},"stopReason":"stop","timestamp":1762966540939}}`

    const results = await parser.parse(testData)

    expect(results).toHaveLength(2)
    expect(results[0].content).toBe('Valid user message')
    expect(results[0].role).toBe('user')
    expect(results[1].content).toBe('Assistant response')
    expect(results[1].role).toBe('assistant')
  })

  it('should handle empty and whitespace-only messages', async () => {
    const testData = `{"type":"message","timestamp":"2025-11-12T16:55:40.961Z","message":{"role":"user","content":[{"type":"text","text":""}],"timestamp":1762966540936}}
{"type":"message","timestamp":"2025-11-12T16:55:40.961Z","message":{"role":"user","content":[{"type":"text","text":"Valid message"}],"timestamp":1762966540936}}
{"type":"message","timestamp":"2025-11-12T16:55:45.575Z","message":{"role":"assistant","content":[{"type":"text","text":"  \n\n \t"}],"api":"anthropic-messages","provider":"anthropic","model":"claude-sonnet-4-5","usage":{"input":3,"output":117,"cacheRead":0,"cacheWrite":1196,"cost":{"input":0.000009,"output":0.001755,"cacheRead":0,"cacheWrite":0.004485,"total":0.006249}},"stopReason":"stop","timestamp":1762966540939}}`

    const results = await parser.parse(testData)

    expect(results).toHaveLength(1)
    expect(results[0].content).toBe('Valid message')
  })

  it('isCommandMessage method should detect command patterns', () => {
    const testCases = [
      { content: '<command-name>/clear</command-name>', expected: true },
      { content: '<command-message>clear</command-message>', expected: true },
      { content: '<command-args></command-args>', expected: true },
      { content: '<local-command-stdout></local-command-stdout>', expected: true },
      { content: 'Caveat: The messages below were generated by the user while running local commands', expected: true },
      { content: 'CAVEAT: The messages below were generated by the user while running local commands', expected: true },
      { content: 'This is a normal message', expected: false },
      { content: 'Some text with <not-a-command> tag', expected: false },
      { content: 'Regular conversation about commands', expected: false },
    ]

    testCases.forEach(({ content, expected }) => {
      // Access private method for testing
      const result = (parser as any).isCommandMessage(content)
      expect(result).toBe(expected)
    })
  })
})
